[tool.uv.workspace]
members = ["packages/shared", "apps/react_agent", "apps/rag_agent"]

[tool.uv]
dev-dependencies = [
    "pytest>=8.3",
    "ruff>=0.5",
    "black>=24.0",
    "mypy>=1.11",
    "pytest-asyncio>=0.23",
    "langgraph-cli[inmem]>=0.4.0",
]

[tool.ruff]
line-length = 100
target-version = "py312"

[tool.mypy]
strict = true
python_version = "3.12"

[tool.black]
line-length = 100
target-version = ["py312"]
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''
