apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-agent
  namespace: langgraph-agents
  labels:
    app: react-agent
    app.kubernetes.io/name: react-agent
    app.kubernetes.io/part-of: langgraph-agent-templates
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-agent
  template:
    metadata:
      labels:
        app: react-agent
    spec:
      containers:
        - name: react-agent
          image: ghcr.io/your-org/react-agent:latest
          ports:
            - containerPort: 2024
              name: http
          env:
            - name: PORT
              value: "2024"
            - name: HOST
              value: "0.0.0.0"
            - name: LOG_LEVEL
              value: "INFO"
            - name: ENVIRONMENT
              value: "production"
          envFrom:
            - secretRef:
                name: react-agent-secrets
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
      securityContext:
        fsGroup: 1000